# Generated by Django 3.2.12 on 2022-04-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('trip_id', models.IntegerField()),
                ('trip_date', models.DateTimeField()),
                ('trip_time', models.TextField()),
                ('trip_cost', models.IntegerField()),
                ('contact_name', models.TextField()),
                ('contact_email', models.TextField()),
                ('contact_phone', models.IntegerField()),
                ('payment', models.TextField()),
                ('prime', models.TextField()),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
